# Generated by Django 3.0.7 on 2020-06-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200615_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
