# Generated by Django 3.0.7 on 2020-06-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_set', to='recipes.Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_needed',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'amount', 'unit')},
        ),
    ]
