# Generated by Django 3.0.7 on 2020-06-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
