# Generated by Django 3.0.7 on 2020-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_auto_20200717_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='prep',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
