# Generated by Django 3.0.7 on 2020-07-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0033_auto_20200719_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
