# Generated by Django 3.0.7 on 2020-07-22 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_recipe_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
    ]
